name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Detect the installed Rust version
        id: rustc
        run: echo "::set-output name=version::$(rustc -V)"

      - name: Cache Cargo's registry cache
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry/cache
          key: cargo-registry-cache-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-registry-cache-

      - name: Cache Cargo's registry index
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry/index
          key: cargo-registry-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-registry-index-

      - name: Cache Cargo's target directory
        uses: actions/cache@v2
        with:
          path: target
          key: cargo-build-${{ steps.rustc.outputs.version }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-build-${{ steps.rustc.outputs.version }}-

        ## This adds the necessary base URL of "https://theseus-os.github.io/blog" to ensure links work in GitHub Pages.
      # - run: sed -i 's/<head>/<head>\n    <base href="https:\/\/theseus-os.github.io\/blog">/' 'templates/layout.hbs'
      - run: cargo run
      - run: cp _config.yml ./site/
      # - run: cp CNAME ./site/
      # - run: touch site/.nojekyll
      - uses: JamesIves/github-pages-deploy-action@releases/v3
        if: github.ref == 'refs/heads/main'
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: github_pages
          FOLDER: site
